# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSearchsanpham():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_searchsanpham(self):
    self.driver.get("https://shoptest.fun/home")
    self.driver.set_window_size(1552, 832)
    self.driver.find_element(By.LINK_TEXT, "Trang Sản phẩm").click()
    self.driver.find_element(By.CSS_SELECTOR, ".search-product .form-control").click()
    self.driver.find_element(By.CSS_SELECTOR, ".search-product .form-control").send_keys("hoa đào ")
    self.driver.find_element(By.CSS_SELECTOR, "button > .fa-search").click()
    self.driver.execute_script("window.scrollBy(0, 500)")
    self.driver.find_element(By.CSS_SELECTOR, ".search-product .form-control").click()
    self.driver.find_element(By.CSS_SELECTOR, ".search-product .form-control").send_keys("quan")
    self.driver.find_element(By.CSS_SELECTOR, "form > button").click()
    self.driver.execute_script("window.scrollBy(0, 500)")
    self.driver.find_element(By.CSS_SELECTOR, ".search-product .form-control").click()
    self.driver.find_element(By.CSS_SELECTOR, ".search-product .form-control").send_keys("áo ")
    self.driver.find_element(By.CSS_SELECTOR, ".search-product .form-control").send_keys(Keys.ENTER)
    self.driver.execute_script("window.scrollBy(0, 500)")
    self.driver.find_element(By.CSS_SELECTOR, ".search-product .form-control").click()
    self.driver.find_element(By.CSS_SELECTOR, ".search-product .form-control").send_keys("Set áo công sở")
    self.driver.find_element(By.CSS_SELECTOR, ".search-product .form-control").send_keys(Keys.ENTER)
    self.driver.execute_script("window.scrollBy(0, 500)")
    assert self.driver.find_element(By.CSS_SELECTOR, ".why-text > h4").text == "Set áo công sở"
  
