# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSignupinvalid():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_dangky03(self):
    self.driver.get("https://shoptest.fun/home")
    self.driver.set_window_size(1552, 832)
    element = self.driver.find_element(By.CSS_SELECTOR, ".our-link li:nth-child(2) > a")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".our-link li:nth-child(2) > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".footer-main").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".col-md-6:nth-child(2) > .form-group:nth-child(1) strong").text == "Please enter full name"
    assert self.driver.find_element(By.CSS_SELECTOR, ".col-md-6:nth-child(2) > .form-group:nth-child(2) strong").text == "Please enter address"
    assert self.driver.find_element(By.CSS_SELECTOR, ".col-md-6:nth-child(2) > .form-group:nth-child(3) strong").text == "Please enter phone"
  
  def test_dangky04(self):
    self.driver.get("https://shoptest.fun/home")
    self.driver.set_window_size(1536, 816)
    self.driver.find_element(By.CSS_SELECTOR, ".our-link li:nth-child(2) > a").click()
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").send_keys("nguyenhuy")
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("huy@gmail.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("abcd1234")
    self.driver.find_element(By.NAME, "password_confirmation").click()
    self.driver.find_element(By.NAME, "password_confirmation").send_keys("abcd1234")
    self.driver.find_element(By.ID, "full_name").click()
    self.driver.find_element(By.ID, "full_name").send_keys("nguyenhuy")
    self.driver.find_element(By.ID, "address").click()
    self.driver.find_element(By.ID, "address").send_keys("sontayhanoi")
    self.driver.find_element(By.ID, "phone_no").click()
    self.driver.find_element(By.ID, "phone_no").send_keys("048")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".invalid-feedback > strong").text == "Phone number must be 10 digits"
  
  def test_dangky02(self):
    self.driver.get("https://shoptest.fun/home")
    self.driver.set_window_size(1552, 832)
    self.driver.find_element(By.CSS_SELECTOR, ".our-link li:nth-child(2) > a").click()
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").send_keys("nguyenhuy")
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("huypanda@gmail.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").click()
    element = self.driver.find_element(By.ID, "password")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.ID, "password")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.ID, "password")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.ID, "password").click()
    element = self.driver.find_element(By.ID, "password")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "password").send_keys("abcd1234")
    self.driver.find_element(By.NAME, "password_confirmation").click()
    self.driver.find_element(By.NAME, "password_confirmation").send_keys("abcd12345")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".nph-rg:nth-child(1)").click()
    assert self.driver.find_element(By.XPATH, "//body[@id=\'bodycontent\']/div[3]/div[3]/div/form/div/div/div[3]/span/strong").text == "Password confirmation does not match."
  
  def test_dangky01(self):
    self.driver.get("https://shoptest.fun/home")
    self.driver.set_window_size(978, 816)
    self.driver.find_element(By.CSS_SELECTOR, ".our-link li:nth-child(2) > a").click()
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").send_keys("huy")
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("huy@")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".col-md-6:nth-child(1) > .form-group:nth-child(2) strong").text == "Email invalid"
  
  def test_dangky05(self):
    self.driver.get("https://shoptest.fun/home")
    self.driver.set_window_size(1536, 816)
    self.driver.find_element(By.CSS_SELECTOR, ".our-link li:nth-child(2) > a").click()
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").send_keys("nguyenhuy")
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("huy@gmail.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("abcd1234")
    self.driver.find_element(By.NAME, "password_confirmation").click()
    self.driver.find_element(By.NAME, "password_confirmation").send_keys("abcd1234")
    self.driver.find_element(By.ID, "full_name").click()
    self.driver.find_element(By.ID, "full_name").send_keys("nguyenhuy")
    self.driver.find_element(By.ID, "address").click()
    self.driver.find_element(By.ID, "address").send_keys("sontayhan")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(2) strong").text == "Minimum address length is 10 characters"
  
