# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSignininvalid():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_dangnhap01(self):
    self.driver.get("https://shoptest.fun/home/home")
    self.driver.set_window_size(1552, 832)
    element = self.driver.find_element(By.LINK_TEXT, "Liên hệ với chúng tôi")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".our-link li:nth-child(1) > a").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("huypanda2001@gmail.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("huy")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".err-login").click()
    assert self.driver.find_element(By.XPATH, "//div[3]/div/div").text == " your username and password are wrong."
    self.driver.find_element(By.CSS_SELECTOR, ".modal-body").click()
  
  def test_dangnhap02(self):
    self.driver.get("https://shoptest.fun/home")
    self.driver.set_window_size(978, 816)
    self.driver.find_element(By.CSS_SELECTOR, ".our-link li:nth-child(1) > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(2) strong").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(3) strong").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(2) strong").text == "Please enter email"
    assert self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(3) strong").text == "Please enter password"
  
  def test_dangnhap03(self):
    self.driver.get("https://shoptest.fun/home")
    self.driver.set_window_size(980, 816)
    self.driver.find_element(By.CSS_SELECTOR, ".our-link > ul").click()
    self.driver.find_element(By.CSS_SELECTOR, ".our-link li:nth-child(1) > a").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("huy")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("abcd1234")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "strong").text == "Email invalid"
  
  def test_dangnhap04(self):
    self.driver.get("https://shoptest.fun/home")
    self.driver.set_window_size(983, 816)
    self.driver.find_element(By.CSS_SELECTOR, ".our-link li:nth-child(1) > a").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("huypanda2001@gmail.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "strong").text == "Please enter password"
  
