# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAddtocart():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_addtocart(self):
    self.driver.get("https://shoptest.fun/home")
    self.driver.set_window_size(1552, 832)
    self.driver.execute_script("window.scrollBy(0, 500)")
    self.driver.find_element(By.LINK_TEXT, "Add to Cart").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fa-shopping-bag").click()
    self.driver.find_element(By.LINK_TEXT, "Giỏ Hàng").click()
    self.driver.find_element(By.CSS_SELECTOR, "a > input").click()
  
