# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDangkycorrcet():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_dangkycorrcet(self):
    self.driver.get("https://shoptest.fun/home")
    self.driver.set_window_size(1552, 832)
    self.driver.find_element(By.CSS_SELECTOR, ".our-link li:nth-child(2) > a").click()
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").send_keys("nguyenhuy01")
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("huypanda2001@gmail.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".wrapper").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".wrapper")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "password").send_keys("abcd1234")
    self.driver.find_element(By.NAME, "password_confirmation").click()
    self.driver.find_element(By.NAME, "password_confirmation").send_keys("abcd1234")
    self.driver.find_element(By.ID, "full_name").click()
    self.driver.find_element(By.ID, "full_name").send_keys("nguyenlehuy01")
    self.driver.find_element(By.CSS_SELECTOR, ".nph-rg:nth-child(2)").click()
    self.driver.find_element(By.ID, "address").click()
    self.driver.find_element(By.ID, "address").send_keys("sontayhanoi")
    self.driver.find_element(By.ID, "phone_no").click()
    self.driver.find_element(By.ID, "phone_no").send_keys("0941589633")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.close()
  
